---

- hosts: all
  become: true
  tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: controller
  become: true
  roles:
    - NTP
    - OpenStack
    - SQL

- hosts: compute
  become: true
  roles:
    - MessageQ
    - Memcached
    - Etcd
