---

  - name: install OpenStack 22.04 LTS
    tags: OpenStack,ubuntu
    apt:
      name:
        - nova-compute
        - python3-openstackclient
      state: latest
    when: ansible_distribution == "Ubuntu"
